language: cpp
sudo: required
dist: trusty
services:
  - docker
python:
  - "2.7"
compiler:
- gcc
os:
- linux
env:
  global:

before_install:
- echo $LANG
- echo $LC_ALL
- test -n $CC && unset CC
before_script:
- echo "install packages"
install:
- sudo apt-get update
- sudo apt-get install libgfortran3 build-essential gfortran gfortran-multilib libquadmath0
script:
- cd src && make cppp; cd ..
- cd src && make d_test; cd ..
- cd src && make -f pest.mak all; cd ..
# make clean
- cd src && make -f ppest.mak all; cd ..
# make clean
- cd src && make -f pestutl1.mak all; cd ..
# make clean
- cd src && make -f pestutl2.mak all; cd ..
# make clean
- cd src && make -f pestutl3.mak all; cd ..
# make clean
- cd src && make -f pestutl4.mak all; cd ..
# make clean
- cd src && make -f pestutl5.mak all; cd ..
# make clean
- cd src && make -f pestutl6.mak all; cd ..
# make clean
- cd src && make -f sensan.mak all; cd ..
# make clean
- cd src && make -f beopest.mak all; cd ..
# make clean
# make install

after_success:
- echo "make docker"
branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email:
  - allixender@googlemail.com
